from datetime import datetime
import json
import re
import time
import urllib.parse
from time import monotonic
from typing import Any

import requests
from bs4 import BeautifulSoup

from scrapers.base_scraper import BaseScraper
from models import ScrapedFanfic
from constants.cp_tags import CPTagConfig, get_keyword_for_platform


def extract_ao3_tag_metadata(work_element) -> tuple[list[str], list[str], list[str]]:
    """Helper to extract relationships, characters, and other tags from an AO3 work blurb tag list."""
    relationships = []
    characters = []
    other = []
    if not work_element:
        return relationships, characters, other
    
    # 支援傳入 ul 或是整個 work blurb 元素
    tag_ul = work_element.select_one("ul.tags") or work_element
    if tag_ul:
        for li in tag_ul.select("li"):
            text = li.get_text(strip=True)
            classes = li.get("class", [])
            if any("relationship" in c.lower() for c in classes):
                relationships.append(text)
            elif any("character" in c.lower() for c in classes):
                characters.append(text)
            else:
                other.append(text)
    return relationships, characters, other


class AO3Scraper(BaseScraper):
    """Best-effort AO3 public search adapter with canonical query semantics."""

    adult_content_cookie = {
        "name": "view_adult",
        "value": "true",
        "domain": "archiveofourown.org",
        "path": "/",
    }
    static_headers = {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9,zh-TW;q=0.8,zh;q=0.7",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
        "Cookie": "view_adult=true; accepted_tos=2018",
    }
    static_cookies = {"view_adult": "true", "accepted_tos": "2018"}
    static_connect_timeout_seconds = 5
    static_read_timeout_seconds = 10
    static_search_budget_seconds = 10
    max_boolean_query_length = 220

    def __init__(self):
        super().__init__()
        self._memory_cache: dict[str, tuple[datetime, dict[str, Any]]] = {}
        self.cache_ttl = 1800  # 30 minutes
        self.last_total_heading: tuple[str, int] | None = None
        self._static_terminal_warning: str | None = None
        self._static_deadline: float | None = None

    @staticmethod
    def build_search_url(keyword: str, page: int = 1, mode: str = "keyword") -> str:
        """Build AO3's native free-text search URL without implicit filters.

        The first page matches the URL generated by AO3's own search form:
        ``commit=Search&work_search[query]=…``. Pagination is the sole optional
        extension and is added only after the user asks for a later page.
        """
        parameters = [
            ("commit", "Search"),
            ("work_search[creators_text]" if mode == "author" else "work_search[query]", keyword),
            ("with_real_author_name", "1"),
        ]
        if page > 1:
            parameters.append(("page", str(page)))
        return f"https://archiveofourown.org/works/search?{urllib.parse.urlencode(parameters)}"

    @staticmethod
    def extract_total_works_from_heading(soup) -> int | None:
        """Extract AO3's displayed total from an explicit result heading only."""
        heading_match = AO3Scraper.extract_total_works_heading(soup)
        return heading_match[1] if heading_match else None

    @staticmethod
    def extract_total_works_heading(soup) -> tuple[str, int] | None:
        """Return the raw AO3 result heading with its parsed total for diagnostics."""
        headings = soup.select("h2.heading, .heading, #main h2, #main h3")
        patterns = (
            r"\b\d[\d,]*\s*[-–]\s*\d[\d,]*\s+of\s+([\d,]+)\s+Works?\b",
            r"\bof\s+([\d,]+)\s+Works?\b",
            r"\b([\d,]+)\s+Works?\s+Found\b",
            r"\b([\d,]+)\s+Found\s*[?？]?\b",
        )
        for heading in headings:
            heading_text = heading.get_text(" ", strip=True)
            for pattern in patterns:
                match = re.search(pattern, heading_text, re.IGNORECASE)
                if match:
                    return heading_text, int(match.group(1).replace(",", ""))
        return None

    def _fetch_static_search_html(self, keyword: str, page: int, mode: str = "keyword") -> str | None:
        """Fetch AO3 HTML once with a bounded ten-second public HTTP budget."""
        url = self.build_search_url(keyword, page, mode)
        for attempt in range(2):
            remaining_budget = (self._static_deadline - monotonic()) if self._static_deadline else 4.0
            if remaining_budget <= 0:
                self._static_terminal_warning = "AO3 靜態搜尋連線逾時或不可用"
                print("[AO3 Static] Shared HTTP budget exhausted; returning bounded source warning")
                return None
            try:
                response = requests.get(
                    url,
                    headers=self.static_headers,
                    cookies=self.static_cookies,
                    timeout=(self.static_connect_timeout_seconds, self.static_read_timeout_seconds),
                )
                remaining_budget = (self._static_deadline - monotonic()) if self._static_deadline else 4.0
                if response.status_code in (503, 525) and attempt == 0 and remaining_budget > 0.6:
                    print(f"[AO3 Static] HTTP {response.status_code}; retrying once after 600ms")
                    time.sleep(0.6)
                    continue
                if response.status_code in (403, 429, 503, 520, 521, 522, 525):
                    self._static_terminal_warning = f"AO3 靜態搜尋暫時不可用（HTTP {response.status_code}）"
                    print(f"[AO3 Static] HTTP {response.status_code}; returning bounded source warning")
                    return None
                response.raise_for_status()
                html = response.text
                page_text = html.casefold()
                if any(marker in page_text for marker in ("cf-chl", "just a moment", "captcha")):
                    self._static_terminal_warning = "AO3 靜態搜尋觸發保護頁"
                    print("[AO3 Static] Protected response; returning bounded source warning")
                    return None
                return html
            except requests.RequestException as error:
                remaining_budget = (self._static_deadline - monotonic()) if self._static_deadline else 0
                if attempt == 0 and remaining_budget > 0.6:
                    print(f"[AO3 Static] Public GET failed; retrying once after 600ms: {error}")
                    time.sleep(0.6)
                    continue
                self._static_terminal_warning = "AO3 靜態搜尋連線逾時或不可用"
                print(f"[AO3 Static] Public GET unavailable; returning bounded source warning: {error}")
                return None
        return None

    def _parse_static_results(self, html: str, keyword: str) -> list[ScrapedFanfic]:
        soup = BeautifulSoup(html, "html.parser")
        items: list[ScrapedFanfic] = []
        for work in soup.select("li.work.blurb"):
            title_el = work.select_one("h4.heading a:first-of-type")
            title = title_el.get_text(strip=True) if title_el else "Untitled work"
            rel_href = title_el.get("href", "") if title_el else ""
            url = f"https://archiveofourown.org{rel_href}" if rel_href.startswith("/") else rel_href
            author_el = work.select_one("h4.heading a[rel='author']")
            author = author_el.get_text(strip=True) if author_el else "Unknown author"
            summary_el = work.select_one("blockquote.userstuff")
            summary = summary_el.get_text(strip=True) if summary_el else ""
            rels, chars, others = extract_ao3_tag_metadata(work)
            word_count_el = work.select_one("dd.words")
            updated_el = work.select_one("p.datetime")
            status_el = work.select_one("dd.status")
            status_text = status_el.get_text(" ", strip=True) if status_el else ""
            if not url or not is_real_url(url):
                continue
            items.append(ScrapedFanfic(
                id=f"ao3:{url}", title=title, author=author, platform="AO3", url=url,
                tags=", ".join(tag for tag in rels + chars + others if tag), relationships=rels,
                characters=chars, summary=summary,
                wordCount=word_count_el.get_text(strip=True) if word_count_el else None,
                updatedAt=updated_el.get_text(strip=True) if updated_el else None,
                isComplete=status_text.casefold().startswith("completed"),
                scraped_at=datetime.utcnow(), keyword=keyword,
            ))
        return items

    def _scrape_static_pages(self, keyword: str, target_pages: list[int], requested_page: int, mode: str = "keyword") -> dict[str, Any] | None:
        """Parse cards and official totals from the same server-rendered documents."""
        items: list[ScrapedFanfic] = []
        total_works = 0
        for target_page in target_pages:
            html = self._fetch_static_search_html(keyword, target_page, mode)
            if html is None:
                return None
            soup = BeautifulSoup(html, "html.parser")
            works = soup.select("li.work.blurb")
            heading_match = self.extract_total_works_heading(soup)
            if not works and heading_match is None and "no results" not in html.casefold():
                return None
            if target_page == requested_page and heading_match:
                self.last_total_heading = heading_match
                total_works = heading_match[1]
                print(f"[AO3 Static] Official result heading: {heading_match[0]!r} => totalWorks={total_works}")
            items.extend(self._parse_static_results(html, keyword))
        total_pages = max(1, (total_works + 19) // 20) if total_works else 1
        print(f"[AO3 Static] Parsed {len(items)} cards from server-rendered search HTML")
        return {"items": items, "total_works": total_works, "total_pages": total_pages}

    def scrape(
        self,
        keyword: str,
        page: int = 1,
        force_refresh: bool = False,
        custom_cp_map: dict[str, CPTagConfig] | None = None,
        mode: str = "keyword",
    ) -> dict[str, Any]:
        self.last_warning = None
        self.last_total_heading = None
        self._static_terminal_warning = None
        trimmed_kw = keyword.strip()
        if not trimmed_kw:
            return {"items": [], "total_works": 0, "total_pages": 1}

        translated_query = trimmed_kw if mode == "author" else get_keyword_for_platform(trimmed_kw, "ao3", custom_cp_map)
        # AO3 accepts free-text search, but relationship aliases contain quoted
        # boolean expressions that can be slow or rejected at the public edge.
        # Send a single literal query for immediate search; the mapping remains
        # available to the vocabulary UI and relevance ranking.
        boolean_markers = (" OR ", " AND ", '"')
        if any(marker in translated_query for marker in boolean_markers):
            ao3_query = trimmed_kw
            print("[AO3 Static] Boolean translation fell back to the original keyword")
        else:
            ao3_query = translated_query

        cache_key = f"{mode}:{trimmed_kw}:page={page}"
        # 強制更新會跳過 Adapter cache；一般 CP 則由 API 的高可信度 TTL 管理。
        bypass_memory_cache = force_refresh
        if bypass_memory_cache:
            self._memory_cache.pop(cache_key, None)
        now = datetime.utcnow()
        if not bypass_memory_cache and cache_key in self._memory_cache:
            cached_time, cached_payload = self._memory_cache[cache_key]
            if (now - cached_time).total_seconds() < self.cache_ttl:
                print(f"[AO3Scraper] Memory cache hit for '{cache_key}'")
                return cached_payload

        # The pure HTTP live-search path makes one bounded request per user page.
        # Loading a second page is deferred to the existing pagination control so
        # an otherwise valid first-page response never delays all platforms.
        target_pages = [page]
        self._static_deadline = monotonic() + self.static_search_budget_seconds
        try:
            static_payload = self._scrape_static_pages(ao3_query, target_pages, page, mode)
        finally:
            self._static_deadline = None
        if static_payload is not None:
            for item in static_payload["items"]:
                item.keyword = trimmed_kw
            if static_payload["items"]:
                self._memory_cache[cache_key] = (now, static_payload)
            return static_payload
        if self._static_terminal_warning:
            self.last_warning = self._static_terminal_warning
            return {"items": [], "total_works": 0, "total_pages": 1}
        self.last_warning = "AO3 靜態搜尋頁未提供可驗證的結果標記"
        return {"items": [], "total_works": 0, "total_pages": 1}


def is_real_url(url: str) -> bool:
    return url.startswith("https://archiveofourown.org/works/")
